export function Footer() {
  return (
    <footer className="bg-ink text-white/70 py-16 border-t border-white/10">
      <div className="container-luxury">
        <div className="grid md:grid-cols-4 gap-10 mb-12">
          <div className="md:col-span-2">
            <h3 className="text-white text-2xl mb-2">Helen Lam</h3>
            <p className="text-sm text-brand uppercase tracking-[0.2em] mb-4">Personal Real Estate Corporation</p>
            <p className="text-sm leading-relaxed max-w-md">
              Trusted real estate professional serving Vancouver, Richmond, Burnaby and Coquitlam — every step of the way.
            </p>
          </div>
          <div>
            <h4 className="text-white text-sm uppercase tracking-wider mb-4">Navigate</h4>
            <ul className="space-y-2 text-sm">
              <li><a href="#listings" className="hover:text-brand transition-smooth">Listings</a></li>
              <li><a href="#services" className="hover:text-brand transition-smooth">Services</a></li>
              <li><a href="#process" className="hover:text-brand transition-smooth">Process</a></li>
              <li><a href="#evaluation" className="hover:text-brand transition-smooth">Home Evaluation</a></li>
              <li><a href="#contact" className="hover:text-brand transition-smooth">Contact</a></li>
            </ul>
          </div>
          <div>
            <h4 className="text-white text-sm uppercase tracking-wider mb-4">Contact</h4>
            <ul className="space-y-2 text-sm">
              <li><a href="tel:778-889-6084" className="hover:text-brand transition-smooth">Cell: 778-889-6084</a></li>
              <li>Office: 604-999-8882</li>
              <li><a href="mailto:sold@helenlam.ca" className="hover:text-brand transition-smooth">sold@helenlam.ca</a></li>
              <li>#215-8600 Cambie Rd<br />Richmond, BC V6X 4J8</li>
            </ul>
          </div>
        </div>
        <div className="pt-8 border-t border-white/10 text-xs text-white/50 space-y-3">
          <p>
            The data relating to real estate on this website comes in part from the MLS® Reciprocity program of the Greater Vancouver REALTORS®, the Fraser Valley Real Estate Board or the Chilliwack and District Real Estate Board. Real estate listings held by participating real estate firms are marked with the MLS® logo and detailed information about the listing includes the name of the listing agent. This representation is based in whole or part on data generated by the listed boards which assume no responsibility for its accuracy. The materials contained on this page may not be reproduced without the express written consent of the listing brokerages.
          </p>
          <p>© {new Date().getFullYear()} Helen Lam Personal Real Estate Corporation · 1NE Collective Realty Inc.</p>
        </div>
      </div>
    </footer>
  );
}
