import logo from "@/assets/1ne-collective-logo.png";
import mls from "@/assets/mls-reciprocity.gif";

export function Footer() {
  return (
    <footer className="bg-ink text-white/70 pt-16 pb-10 border-t border-white/10">
      <div className="container-luxury">
        <div className="grid md:grid-cols-12 gap-10 mb-12">
          <div className="md:col-span-5">
            <h3 className="text-white text-2xl tracking-display font-semibold">HELEN LAM</h3>
            <p className="text-xs text-brand-light uppercase tracking-eyebrow mt-1 mb-5">Personal Real Estate Corporation</p>
            <p className="text-sm leading-relaxed max-w-md mb-6 font-light">
              Trusted real estate professional serving Vancouver, Richmond, Burnaby and Coquitlam — every step of the way.
            </p>
            <div className="bg-white/95 inline-flex items-center px-5 py-3 rounded-sm">
              <img src={logo} alt="1NE Collective Realty" className="h-12 w-auto" loading="lazy" />
            </div>
          </div>
          <div className="md:col-span-3">
            <h4 className="text-white text-xs uppercase tracking-eyebrow mb-5 font-semibold">Navigate</h4>
            <ul className="space-y-3 text-sm">
              <li><a href="#listings" className="hover:text-brand-light transition-smooth">Listings</a></li>
              <li><a href="#services" className="hover:text-brand-light transition-smooth">Services</a></li>
              <li><a href="#process" className="hover:text-brand-light transition-smooth">Process</a></li>
              <li><a href="#evaluation" className="hover:text-brand-light transition-smooth">Home Evaluation</a></li>
              <li><a href="#contact" className="hover:text-brand-light transition-smooth">Contact</a></li>
            </ul>
          </div>
          <div className="md:col-span-4">
            <h4 className="text-white text-xs uppercase tracking-eyebrow mb-5 font-semibold">Contact</h4>
            <ul className="space-y-3 text-sm">
              <li><a href="tel:778-889-6084" className="hover:text-brand-light transition-smooth">Cell: 778-889-6084</a></li>
              <li>Office: 604-999-8882</li>
              <li><a href="mailto:sold@helenlam.ca" className="hover:text-brand-light transition-smooth">sold@helenlam.ca</a></li>
              <li className="leading-relaxed">#215-8600 Cambie Rd<br />Richmond, BC V6X 4J8</li>
            </ul>
          </div>
        </div>
        <div className="pt-8 border-t border-white/10">
          <div className="flex items-start gap-4 mb-6">
            <img src={mls} alt="MLS Reciprocity" className="h-10 w-auto shrink-0 mt-1" loading="lazy" />
            <p className="text-[11px] text-white/50 leading-relaxed">
              The data relating to real estate on this website comes in part from the MLS® Reciprocity program of the Greater Vancouver REALTORS®, the Fraser Valley Real Estate Board or the Chilliwack and District Real Estate Board. Real estate listings held by participating real estate firms are marked with the MLS® logo and detailed information about the listing includes the name of the listing agent. This representation is based in whole or part on data generated by the listed boards which assume no responsibility for its accuracy. The materials contained on this page may not be reproduced without the express written consent of the listing brokerages.
            </p>
          </div>
          <p className="text-xs text-white/40">© {new Date().getFullYear()} Helen Lam Personal Real Estate Corporation · 1NE Collective Realty Inc.</p>
        </div>
      </div>
    </footer>
  );
}
